ls:
  .js: regex:[+_]?[a-z0-9\-\.]+
  .ts: regex:[+_]?[a-z0-9\-\.]+
  .d.ts: kebab-case
  .svelte: regex:[+_]?[a-z0-9\-\.]+

ignore:
  - .git
  - .histoire
  - .svelte-kit
  - .vercel
  - build
  - node_modules
  - dist
  - server
